"""Add mod_channel column to Channel model

Revision ID: 02141f32309c
Revises: b57590732323
Create Date: 2021-01-15 20:45:15.434766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02141f32309c'
down_revision = 'b57590732323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('mod_channel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'mod_channel')
    # ### end Alembic commands ###
