"""Add switch friend codes to friendcodes table

Revision ID: 8441e56ee5a9
Revises: 8555ae8f01e0
Create Date: 2021-08-17 19:29:11.634084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8441e56ee5a9'
down_revision = '8555ae8f01e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendcodes', sa.Column('fc_switch', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendcodes', 'fc_switch')
    # ### end Alembic commands ###
