"""Add whitelist table for levenshtein filter

Revision ID: 8555ae8f01e0
Revises: 2bcb16a1fa03
Create Date: 2021-08-16 02:33:13.532896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8555ae8f01e0'
down_revision = '2bcb16a1fa03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelistedwords',
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelistedwords')
    # ### end Alembic commands ###
