"""Add staff_only column to voteviews

Revision ID: 86ed34559d98
Revises: 18c5ec7bf887
Create Date: 2022-05-08 20:40:45.167791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ed34559d98'
down_revision = '18c5ec7bf887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voteviews', sa.Column('staff_only', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voteviews', 'staff_only')
    # ### end Alembic commands ###
