"""Added Levenshtein Table

Revision ID: dc5f272ffa13
Revises: a1776e2b764c
Create Date: 2021-07-29 21:55:12.338187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5f272ffa13'
down_revision = 'a1776e2b764c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levenshteinwords',
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('levenshteinwords')
    # ### end Alembic commands ###
