"""First revision

Revision ID: fbf90b8f8171
Revises: 
Create Date: 2020-11-03 20:17:05.012678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf90b8f8171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('approvedinvites',
                    sa.Column('code', sa.String(), nullable=False),
                    sa.Column('uses', sa.Integer(), nullable=True),
                    sa.Column('alias', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('code')
                    )
    op.create_table('channels',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.Unicode(), nullable=True),
                    sa.Column('private', sa.Boolean(), nullable=True),
                    sa.Column('nofilter', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('filteredwords',
                    sa.Column('word', sa.String(), nullable=False),
                    sa.Column('kind', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('word')
                    )
    op.create_table('flags',
                    sa.Column('name', sa.String(length=20), nullable=False),
                    sa.Column('value', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('name')
                    )
    op.create_table('members',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('watched', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.Unicode(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('friendcodes',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('fc_3ds', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('permanentroles',
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'role_id', name='permanentroles_pkey')
                    )
    op.create_table('softbans',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('user', sa.BigInteger(), nullable=True),
                    sa.Column('issuer', sa.BigInteger(), nullable=True),
                    sa.Column('reason', sa.Unicode(), nullable=True),
                    sa.ForeignKeyConstraint(['issuer'], ['members.id'], ),
                    sa.ForeignKeyConstraint(['user'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('staff',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('position', sa.String(length=8), nullable=True),
                    sa.Column('console', sa.String(length=8), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('timed_restriction',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('user', sa.BigInteger(), nullable=True),
                    sa.Column('type', sa.String(length=12), nullable=True),
                    sa.Column('end_date', sa.DateTime(), nullable=True),
                    sa.Column('alerted', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['user'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('warns',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('user', sa.BigInteger(), nullable=True),
                    sa.Column('issuer', sa.BigInteger(), nullable=True),
                    sa.Column('reason', sa.Unicode(), nullable=True),
                    sa.ForeignKeyConstraint(['issuer'], ['members.id'], ),
                    sa.ForeignKeyConstraint(['user'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warns')
    op.drop_table('timed_restriction')
    op.drop_table('staff')
    op.drop_table('softbans')
    op.drop_table('permanentroles')
    op.drop_table('friendcodes')
    op.drop_table('roles')
    op.drop_table('members')
    op.drop_table('flags')
    op.drop_table('filteredwords')
    op.drop_table('channels')
    op.drop_table('approvedinvites')
    # ### end Alembic commands ###
